### ISSUE TITLE
urgent: recording filename

### ISSUE THREAD

**Issue by michaelpalumbo** [dispersionlab/gitshow11#1]
Hi @reginalluna 

Can you take care of this (and the other issue i just created) before class? I need to reassign write privileges to the repos and want to make sure your repo has your versions of **all files needed.**

1. I see that I named the recording file recording-001.wav by mistake (is supposed to be 'recording.wav'.), and that there are two recording files. Sorry about that. It's a remnant from an earlier phase of the research.

Remember that we only want one recording in the repository, and it needs to be named recording.wav.

Can you make sure that when you submit the recording, that it is named exactly recording.wav, and that you remove the recording-001.wav file. 

Then commit and push.

**Comment by reginalluna** [comment]
Yes, I can do that. I will confirm the name of the file.
