### ISSUE TITLE
urgent: need your 4 artefact files

### ISSUE THREAD

**Issue by michaelpalumbo** [dispersionlab/gitshow11#2]
hi @reginalluna 

Can you please push your versions of the following files:

- recording.wav
- score.md
- reflections.md
- patch.vcv

This was due Sunday @ 11:59pm. Can you have it in before class today? If it helps you to submit it in time, don't concern yourself so much with the idea of a 'finished state' of each file. I just need your contributions for each one (each one must be changed by you...)

**Comment by reginalluna** [comment]
Hi Michael,

I pushed it on Sunday night, but I don't know why it didn't have any change
there.

**Comment by michaelpalumbo** [comment]
the only commits at origin are the ones you made to the README.md, which we've resolved. can you please run 
```shell
git log
``` 

in terminal in your version of gitshow11, and paste the printout here? that way we can know if you've actually made more commits that need to be pushed. 

then, please run 
```shell 
git status
```
and post the results from that here too.

**Comment by reginalluna** [comment]
No, I did push it. But I don't know why it only shows up the change of
README.md. Ok, I make it again now.

**Comment by reginalluna** [comment]
it still doesn't work. ....

**Comment by reginalluna** [comment]
when I ran *git log*, it only shows the change I made on Friday, and
actually it's the change I made on Github's website directly.

I don't understand...

**Comment by michaelpalumbo** [comment]
and git status???

1A: If there are no changes in the status, then you need to pull the
changes from github before proceeding. run 'git pull'.

1B: if there ARE changes, commit them first, then run git pull.

2: then try pushing.

**Comment by reginalluna** [comment]
it's the same when I ran *git status*.  I don't understand, but I gotta
head to the campus now. I can show you my computer later.

**Comment by michaelpalumbo** [comment]
Ok, we can take a look. Thanks for trying all this time and for being so responsive!

**Comment by reginalluna** [comment]
Thanks to all your help. I bet you can help me figure out the problem
there, coz I'm not familiar with the other functions except the tools for
visual/ architecture design on MBP

**Comment by michaelpalumbo** [comment]
Sounds good. lets try either on the first break or during the prep for the
score performances in the first hour
