### ISSUE TITLE
wait until update

### ISSUE THREAD

**Issue by michaelpalumbo** [dispersionlab/gitshow11#3]
Hi @SquidPr0Quo can you wait until @reginalluna uploads her recording before you clone this repo for this week?

@reginalluna can you please upload it asap and reply to this thread once this is done so that Andrew can clone? thanks!

**Comment by SquidPr0Quo** [comment]
Yeah for sure

**Comment by reginalluna** [comment]
Yes! I'm trying to fix the no sound problem of my recording file. Will
finish it asap.

R

**Comment by SquidPr0Quo** [comment]
No worries, take however much time you need.

**Comment by reginalluna** [comment]
Thx Andrew! Anyway, I will fix it soon

R

**Comment by michaelpalumbo** [comment]
Moved from the main repo assignment thread:

>Thank you so much, Michael! I'm having a problem with the recording function that the file doesn't have any sound there. I need to check the solution online. R

Have you checked that you're plugging the input cable(s) to the L/mono and right inputs (the bottom row of inputs) whereas the top row of inputs are gates to start/stop the recorder using signals. Also, have you verified signals are makiing it to the recorder? Can you run them to a scope module to be sure?

**Comment by reginalluna** [comment]
@SquidPr0Quo  Hi, Andrew! The recording file just uploaded!

**Comment by michaelpalumbo** [comment]
Thanks @reginalluna
