### ISSUE TITLE
one thing to do before pushing!

### ISSUE THREAD

**Issue by michaelpalumbo** [dispersionlab/gitshow11#4]
Hi @reginalluna 

Please do this *before* you attempt to push:

You need to *pull*:

```shell
git pull
```

The reason is that I have updated this repo since class (modified the readme and removed the errant recording-001.wav file). So your procedure should be

1. run git status
2. if you need to commit, commit. 
3. run git pull to bring my changes into your repo
4. then run git push to push your changes up to github.

**Comment by reginalluna** [comment]
Thank you so much for the notice!!!

**Comment by reginalluna** [comment]
@michaelpalumbo  The recording file just uploaded. Can you see that?

**Comment by michaelpalumbo** [comment]
@reginalluna yes thanks!

@SquidPr0Quo if you haven't already, you can start
